# Uploading the Dataset

In [1]:
#Import libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Sequential 
from keras.preprocessing import image 
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten,Dropout
from tensorflow.keras.optimizers import SGD, Adam
from keras.utils import np_utils



In [4]:
#Import the csv file

face_data = pd.read_csv('Data/fer2013.csv')
face_data

emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
...        ...                                                ...          ...
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 columns]

# Emotions row 
0 = anger
1 - disgust
2 - fear
3 - happiness
4 - sad
5 - surprise 
6 - neutral

In [6]:
#create empty arrays to store the data for the training and testing
X_train = []
y_train = []
X_test = []
y_test = []


#iterate the data and split it into the arrays 
for index, row in face_data.iterrows():
    k = row['pixels'].split(' ')
    if row['Usage'] == 'Training':
        X_train.append(np.array(k,'float64'))
        y_train.append(row['emotion'])
        
    elif row ['Usage'] == 'Public Test':
        X_test.append(np.array(k,'float64'))
        y_test.append(row['emotion'])

# Shape the arrays 

In [7]:


#convert the arrays into numpy 
X_train = np.array(X_train, "float64")
y_train = np.array(y_train,"float64")

X_test = np.array(X_test,"float64")
y_test = np.array(y_train,"float64")



In [8]:
#reshape (pixels 48 x 48 and 1 for greyscale)
X_train = X_train.reshape(X_train.shape[0],48,48,1)
X_test = X_test.reshape(X_test.shape[0],48,48,1)

In [12]:
X_train

array([[[[ 70.],
         [ 80.],
         [ 82.],
         ...,
         [ 52.],
         [ 43.],
         [ 41.]],

        [[ 65.],
         [ 61.],
         [ 58.],
         ...,
         [ 56.],
         [ 52.],
         [ 44.]],

        [[ 50.],
         [ 43.],
         [ 54.],
         ...,
         [ 49.],
         [ 56.],
         [ 47.]],

        ...,

        [[ 91.],
         [ 65.],
         [ 42.],
         ...,
         [ 72.],
         [ 56.],
         [ 43.]],

        [[ 77.],
         [ 82.],
         [ 79.],
         ...,
         [105.],
         [ 70.],
         [ 46.]],

        [[ 77.],
         [ 72.],
         [ 84.],
         ...,
         [106.],
         [109.],
         [ 82.]]],


       [[[151.],
         [150.],
         [147.],
         ...,
         [129.],
         [140.],
         [120.]],

        [[151.],
         [149.],
         [149.],
         ...,
         [122.],
         [141.],
         [137.]],

        [[151.],
         [151.],
      

In [13]:
X_test

array([], shape=(0, 48, 48, 1), dtype=float64)

In [9]:
y_train=np_utils.to_categorical(y_train,num_classes = 7)
y_test=np_utils.to_categorical(y_test,num_classes = 7)

In [10]:
y_train


array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [11]:
y_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

# Convolutional Neural Network (CNN)

In [16]:
model = Sequential()
model.add(Conv2D(input_shape=(X_train.shape[1:]),filters = 64,kernel_size = (3,3), padding = "same", activation = "relu"))
model.add(Conv2D(filters = 64,kernel_size = (3,3), padding = "same", activation = "relu"))       
model.add(MaxPool2D(pool_size = (2,2),strides=(2,2)))             
                 